### ISSUE TITLE
Unmark 1.8 checklist

### ISSUE THREAD

**Issue by cdevroe** [cdevroe/unmark#174]
Things left to do for version 1.8 - codename: 
- [x] Stop editing button doesn't work
- [x] Labelling doesn't work
- [x] Mobile navigation interactions
- [x] Check all internal features styling (featured links, payments, etc.)
- [x] Move search box into List Header
- [x] Remove search from navigation
- [x] Force navigation to be always open on load
- [x] Remove labels from navigation and put under Main List
- [x] Remove "click" on entire mark row

**Comment by cdevroe** [comment]
- [ ] View mark info button doesn't work on "page 2" in infinite scroll

**Comment by kyleruane** [comment]
[ ] Hide sidebar unless editing mark

**Comment by cdevroe** [comment]
- [ ] Edit Mark title
